### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by stevenrayesky** [gregoryjpark/threegoodthings#24]
1. Find font for site
2. logo
3. color scheme

**Comment by gregoryjpark** [comment]
Landing page shows:

carousel of good things, one at a time (hand-picked?)
big Get Started button
How it Works button (scrolls page down)
How it works description/explainer
Three good things is a daily exercise that ....
Create an account and set a daily reminder. We'll remind you every day.
Write your three good things!
big Get Started button

**Comment by stevenrayesky** [comment]
* Buttons for OmniAuth login.

**Comment by gregoryjpark** [comment]
breaking into smaller issues
