### ISSUE TITLE
Model and Table for wellbeing scores

### ISSUE THREAD

**Issue by gregoryjpark** [gregoryjpark/threegoodthings#31]
# Score 
add model (Score) and table (scores) where each record has:

- user_id: integer
- attributes for each individual scale item
- attribute for total scale score 
- created_at: datetime

#### Scale of Positive and Negative Experience

![screen shot 2016-02-03 at 10 18 51 am](https://cloud.githubusercontent.com/assets/7684516/12786540/8ad5d3ec-ca5f-11e5-9fea-1d10ede521ad.png)

![screen shot 2016-02-03 at 10 42 01 am](https://cloud.githubusercontent.com/assets/7684516/12787297/daae8b2c-ca62-11e5-9f07-c7ff2e572e39.png)

#### Satisfaction with Life (SWL) Scale 
![screen shot 2016-02-03 at 10 20 52 am](https://cloud.githubusercontent.com/assets/7684516/12786604/d304035a-ca5f-11e5-9ce8-dec7986a6d9e.png)

###### Reference for SWL
Kobau, R., Sniezek, J., Zack, M. M., Lucas, R. E., & Burns, A. (2010). Well‐being assessment: An evaluation of well‐being scales for public health and population estimates of well‐being among US adults. Applied Psychology: Health and Well-being, 2(3), 272-297. doi:http://dx.doi.org/10.1111/j.1758-0854.2010.01035.x

**Comment by gregoryjpark** [comment]
At signup, user completes both scales and a single score record is added

**Comment by gregoryjpark** [comment]
- At a minimum, users can see the scale scores
- At best, they see a visualization (line graph over time) of their scores

**Comment by stevenrayesky** [comment]
Closed issue with last merge form score_model_table
